services:
  ctf-box:
    image: simone02/vuln-gallery-ctf:v1
    container_name: ctf-challenge-box
    networks:
      ctf_net:
        ipv4_address: 172.20.0.10
    tty: true
    stdin_open: true

networks:
  ctf_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24